public class Constants {
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final Integer FLIGHT_DELETION_PERIOD_DAYS = 30;
    public static final String EMAIL_SETTING_NAME_FLIGHT_CLEANER = 'settings_FlightCleanerBatch';
    public static final String EMAIL_SUBJECT_FLIGHT_CLEANER = 'Batch Process Completed';
    public static final String URI_PARAMETER_FUZZYNAME = 'fuzzyname';
    public static final String URI_PARAMETER_AGE = 'age';
    public static final String RESPONSE_BODY_NAME_EMPTY = 'The name must be not empty';
    public static final String RESPONSE_BODY_AGE_NOT_NUMBER = 'The age must be a number';
    public static final String API_KEY_WEATHERBIT = '13b0d074bc9e41cbbd2865cf3a8884cc';
    public static final String WEATHERBIT_JSON_RESPONSE_BODY_DATA_KEY = 'data';
    public static final String WEATHERBIT_JSON_RESPONSE_BODY_FORECAST_DATE_KEY = 'valid_date';
    public static final String WEATHERBIT_JSON_RESPONSE_BODY_AVERAGE_TEMPERATURE_KEY = 'temp';
    public static final String WEATHERBIT_REQUEST_METHOD_GET = 'GET';
    public static final Integer STATUS_CODE_200 = 200;
    public static final Integer STATUS_CODE_404 = 404;
    public static final Integer STATUS_CODE_409 = 409;
}