public class Constants {
    public static final String FLIGHT_STATUS_DECLINED = 'Declined';
    public static final Integer FLIGHT_DELETION_PERIOD_DAYS = 30;
    public static final String EMAIL_SETTING_NAME_FLIGHT_CLEANER = 'settings_FlightCleanerBatch';
    public static final String EMAIL_SUBJECT_FLIGHT_CLEANER = 'Batch Process Completed';
    public static final String RESPONSE_BODY_NAME_EMPTY = 'The name must be not empty';
    public static final String RESPONSE_BODY_AGE_NOT_NUMBER = 'The age must be a number';
}